import { getCardData, getModData, getTimelineData, getTypeData } from "./banshee-44-mods.js"
import { data } from "./test-data.json"

test("(Integration) api.banshee44mods.com - getModData", async () => {
  const modData = await getModData()
  expect(modData.length === 365)
  expect(modData[0].timestamp).toBeDefined
  expect(modData[0].mods[0].name).toBeDefined
  expect(modData[0].mods[0].type).toBeDefined
  expect(modData[0].mods[0].description).toBeDefined
  expect(modData[0].mods[0].icon).toBeDefined
  expect(modData[0].mods[1].name).toBeDefined
  expect(modData[0].mods[1].type).toBeDefined
  expect(modData[0].mods[1].description).toBeDefined
  expect(modData[0].mods[1].icon).toBeDefined
})

test("(Unit) api.banshee44mods.com - getTimelineData", async () => {
  const timelineData = await getTimelineData(data)
  expect(timelineData[0].month).toBe("2020-03")
  expect(timelineData[0]["Weapon Mod"]).toBe(2)
  expect(timelineData[0]["Armor Mod"]).toBe(2)

  expect(timelineData[1].month).toBe("2020-04")
  expect(timelineData[1]["Weapon Mod"]).toBe(30)
  expect(timelineData[1]["Armor Mod"]).toBe(28)
  expect(timelineData[1]["Charged with Light Mod"]).toBe(2)

  expect(timelineData[2].month).toBe("2020-05")
  expect(timelineData[2]["Weapon Mod"]).toBe(31)
  expect(timelineData[2]["Armor Mod"]).toBe(28)
  expect(timelineData[2]["Charged with Light Mod"]).toBe(3)

  expect(timelineData[3].month).toBe("2020-06")
  expect(timelineData[3]["Weapon Mod"]).toBe(30)
  expect(timelineData[3]["Armor Mod"]).toBe(27)
  expect(timelineData[3]["Charged with Light Mod"]).toBe(3)

  expect(timelineData[4].month).toBe("2020-07")
  expect(timelineData[4]["Weapon Mod"]).toBe(31)
  expect(timelineData[4]["Armor Mod"]).toBe(24)
  expect(timelineData[4]["Charged with Light Mod"]).toBe(2)
  expect(timelineData[4]["Warmind Cell Mod"]).toBe(5)

  expect(timelineData[5].month).toBe("2020-08")
  expect(timelineData[5]["Weapon Mod"]).toBe(31)
  expect(timelineData[5]["Armor Mod"]).toBe(26)
  expect(timelineData[5]["Charged with Light Mod"]).toBe(3)
  expect(timelineData[5]["Warmind Cell Mod"]).toBe(2)

  expect(timelineData[6].month).toBe("2020-09")
  expect(timelineData[6]["Weapon Mod"]).toBe(30)
  expect(timelineData[6]["Armor Mod"]).toBe(24)
  expect(timelineData[6]["Charged with Light Mod"]).toBe(4)
  expect(timelineData[6]["Warmind Cell Mod"]).toBe(2)

  expect(timelineData[7].month).toBe("2020-10")
  expect(timelineData[7]["Weapon Mod"]).toBe(31)
  expect(timelineData[7]["Armor Mod"]).toBe(24)
  expect(timelineData[7]["Charged with Light Mod"]).toBe(3)
  expect(timelineData[7]["Warmind Cell Mod"]).toBe(4)

  expect(timelineData[8].month).toBe("2020-11")
  expect(timelineData[8]["Weapon Mod"]).toBe(30)
  expect(timelineData[8]["Armor Mod"]).toBe(22)
  expect(timelineData[8]["Charged with Light Mod"]).toBe(7)
  expect(timelineData[8]["Warmind Cell Mod"]).toBe(1)

  expect(timelineData[9].month).toBe("2020-12")
  expect(timelineData[9]["Weapon Mod"]).toBe(31)
  expect(timelineData[9]["Armor Mod"]).toBe(22)
  expect(timelineData[9]["Charged with Light Mod"]).toBe(6)
  expect(timelineData[9]["Warmind Cell Mod"]).toBe(3)

  expect(timelineData[10].month).toBe("2021-01")
  expect(timelineData[10]["Weapon Mod"]).toBe(31)
  expect(timelineData[10]["Armor Mod"]).toBe(22)
  expect(timelineData[10]["Charged with Light Mod"]).toBe(4)
  expect(timelineData[10]["Warmind Cell Mod"]).toBe(5)

  expect(timelineData[11].month).toBe("2021-02")
  expect(timelineData[11]["Weapon Mod"]).toBe(28)
  expect(timelineData[11]["Armor Mod"]).toBe(20)
  expect(timelineData[11]["Charged with Light Mod"]).toBe(4)
  expect(timelineData[11]["Warmind Cell Mod"]).toBe(4)

  expect(timelineData[12].month).toBe("2021-03")
  expect(timelineData[12]["Weapon Mod"]).toBe(30)
  expect(timelineData[12]["Armor Mod"]).toBe(18)
  expect(timelineData[12]["Charged with Light Mod"]).toBe(5)
  expect(timelineData[12]["Warmind Cell Mod"]).toBe(7)
})

test("(Unit) api.banshee44mods.com - getTimelineData", async () => {
  const typeData = await getTypeData(data)
  expect(typeData.weaponMods).toBe(15)
  expect(typeData.armorMods).toBe(133)
})

test("(Unit) api.banshee44mods.com - getCardData", async () => {
  const cardData = await getCardData(data)
  /* eslint-disable max-len */
  expect(cardData[0].name).toBe("Backup Mag")
  expect(cardData[0].type).toBe("Weapon Mod")
  expect(cardData[0].description).toBe("Increases magazine.")
  expect(cardData[0].icon).toBe("https://bungie.net/common/destiny2_content/icons/a6bb5abff979e398b0f417040b091171.jpg")
  expect(cardData[0].timesSold).toBe(32)
  expect(cardData[0].lastSold).toBe("2021-03-30")
  expect(cardData[1].name).toBe("Precisely Charged")
  expect(cardData[1].type).toBe("Charged with Light Mod")
  expect(cardData[1].description).toBe("Become Charged with Light by getting multiple rapid precision final blows with Linear Fusion Rifles or Sniper Rifles.")
  expect(cardData[1].icon).toBe("https://bungie.net/common/destiny2_content/icons/13d7d5a897651438d055d64942c1ff4f.png")
  expect(cardData[1].timesSold).toBe(1)
  expect(cardData[1].lastSold).toBe("2021-03-30")
  expect(cardData[2].name).toBe("Quick Access Sling")
  expect(cardData[2].type).toBe("Weapon Mod")
  expect(cardData[2].description).toBe("Swap weapons much faster for a short duration after emptying the magazine.")
  expect(cardData[2].icon).toBe("https://bungie.net/common/destiny2_content/icons/da4d74b0d8ee25ca038d4053811573fc.jpg")
  expect(cardData[2].timesSold).toBe(8)
  expect(cardData[2].lastSold).toBe("2021-03-29")
  expect(cardData[3].name).toBe("Shotgun Targeting")
  expect(cardData[3].type).toBe("Armor Mod")
  expect(cardData[3].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Shotguns.")
  expect(cardData[3].icon).toBe("https://bungie.net/common/destiny2_content/icons/676aeec6afa47c9d915daf4b8fe68ab6.png")
  expect(cardData[3].timesSold).toBe(2)
  expect(cardData[3].lastSold).toBe("2021-03-29")
  expect(cardData[4].name).toBe("Sprint Grip")
  expect(cardData[4].type).toBe("Weapon Mod")
  expect(cardData[4].description).toBe("Temporarily increases the weapon's ready speed and aim down sights speed after sprinting.")
  expect(cardData[4].icon).toBe("https://bungie.net/common/destiny2_content/icons/8e7b5d4045da59ca6e4ff3f56f458c1e.jpg")
  expect(cardData[4].timesSold).toBe(20)
  expect(cardData[4].lastSold).toBe("2021-03-28")
  expect(cardData[5].name).toBe("Wrath of Rasputin")
  expect(cardData[5].type).toBe("Warmind Cell Mod")
  expect(cardData[5].description).toBe("Solar splash damage final blows have a chance to create Warmind Cells.")
  expect(cardData[5].icon).toBe("https://bungie.net/common/destiny2_content/icons/5f066e7b42e77905e008511d02c2ea32.png")
  expect(cardData[5].timesSold).toBe(4)
  expect(cardData[5].lastSold).toBe("2021-03-28")
  expect(cardData[6].name).toBe("Rocket Launcher Ammo Finder")
  expect(cardData[6].type).toBe("Armor Mod")
  expect(cardData[6].description).toBe("Increases your chance of finding Heavy ammo while you have a Rocket Launcher equipped.")
  expect(cardData[6].icon).toBe("https://bungie.net/common/destiny2_content/icons/2b68b4265777e980448252610500c441.png")
  expect(cardData[6].timesSold).toBe(3)
  expect(cardData[6].lastSold).toBe("2021-03-27")
  expect(cardData[7].name).toBe("Freehand Grip")
  expect(cardData[7].type).toBe("Weapon Mod")
  expect(cardData[7].description).toBe("Increases accuracy and ready speed while firing from the hip.")
  expect(cardData[7].icon).toBe("https://bungie.net/common/destiny2_content/icons/be859239d1f36a1516b6d088001ebd32.jpg")
  expect(cardData[7].timesSold).toBe(37)
  expect(cardData[7].lastSold).toBe("2021-03-26")
  expect(cardData[8].name).toBe("Quick Charge")
  expect(cardData[8].type).toBe("Charged with Light Mod")
  expect(cardData[8].description).toBe("Become Charged with Light by rapidly defeating multiple combatants with Fusion Rifles or Shotguns.")
  expect(cardData[8].icon).toBe("https://bungie.net/common/destiny2_content/icons/e80f0a325b78190e164810724044776e.png")
  expect(cardData[8].timesSold).toBe(4)
  expect(cardData[8].lastSold).toBe("2021-03-26")
  expect(cardData[9].name).toBe("Rampage Spec")
  expect(cardData[9].type).toBe("Weapon Mod")
  expect(cardData[9].description).toBe("Increases duration of Rampage.")
  expect(cardData[9].icon).toBe("https://bungie.net/common/destiny2_content/icons/b3eadd1fcadf34e389fad3e7a75acc26.jpg")
  expect(cardData[9].timesSold).toBe(15)
  expect(cardData[9].lastSold).toBe("2021-03-25")
  expect(cardData[10].name).toBe("Heavy Handed")
  expect(cardData[10].type).toBe("Charged with Light Mod")
  expect(cardData[10].description).toBe("While Charged with Light, regain half of your melee energy when you use a charged melee ability, consuming one stack of Charged with Light.")
  expect(cardData[10].icon).toBe("https://bungie.net/common/destiny2_content/icons/c6d1db58becc093aa5d7b2534af41005.png")
  expect(cardData[10].timesSold).toBe(8)
  expect(cardData[10].lastSold).toBe("2021-03-25")
  expect(cardData[11].name).toBe("Dragonfly Spec")
  expect(cardData[11].type).toBe("Weapon Mod")
  expect(cardData[11].description).toBe("Increases the radius and damage of Dragonfly.")
  expect(cardData[11].icon).toBe("https://bungie.net/common/destiny2_content/icons/bb2c1c71fa26132557b1e75515df8c45.jpg")
  expect(cardData[11].timesSold).toBe(6)
  expect(cardData[11].lastSold).toBe("2021-03-24")
  expect(cardData[12].name).toBe("Sidearm Reserves")
  expect(cardData[12].type).toBe("Armor Mod")
  expect(cardData[12].description).toBe("Increases the amount of Sidearm ammo you can carry.")
  expect(cardData[12].icon).toBe("https://bungie.net/common/destiny2_content/icons/ed993c2a0662ae820957dfe00938d18d.png")
  expect(cardData[12].timesSold).toBe(2)
  expect(cardData[12].lastSold).toBe("2021-03-24")
  expect(cardData[13].name).toBe("Radar Booster")
  expect(cardData[13].type).toBe("Weapon Mod")
  expect(cardData[13].description).toBe("Slightly increases the range at which radar detects enemies.")
  expect(cardData[13].icon).toBe("https://bungie.net/common/destiny2_content/icons/2a9af15b6da28299230919bee2072c53.jpg")
  expect(cardData[13].timesSold).toBe(6)
  expect(cardData[13].lastSold).toBe("2021-03-23")
  expect(cardData[14].name).toBe("Shotgun Scavenger")
  expect(cardData[14].type).toBe("Armor Mod")
  expect(cardData[14].description).toBe("Shotguns get bonus reserves when you pick up Special ammo.")
  expect(cardData[14].icon).toBe("https://bungie.net/common/destiny2_content/icons/3197f9d1cfea5f72e9d09cf5b465c226.png")
  expect(cardData[14].timesSold).toBe(2)
  expect(cardData[14].lastSold).toBe("2021-03-23")
  expect(cardData[15].name).toBe("Targeting Adjuster")
  expect(cardData[15].type).toBe("Weapon Mod")
  expect(cardData[15].description).toBe("This weapon gains better target acquisition.")
  expect(cardData[15].icon).toBe("https://bungie.net/common/destiny2_content/icons/34959be63128a82fe6382b800b2d775d.jpg")
  expect(cardData[15].timesSold).toBe(40)
  expect(cardData[15].lastSold).toBe("2021-03-21")
  expect(cardData[16].name).toBe("Pulse Rifle Reserves")
  expect(cardData[16].type).toBe("Armor Mod")
  expect(cardData[16].description).toBe("Increases the amount of Pulse Rifle ammo you can carry.")
  expect(cardData[16].icon).toBe("https://bungie.net/common/destiny2_content/icons/45586aa74c3855d2ca63ce24854fbc4f.png")
  expect(cardData[16].timesSold).toBe(2)
  expect(cardData[16].lastSold).toBe("2021-03-21")
  expect(cardData[17].name).toBe("Sidearm Loader")
  expect(cardData[17].type).toBe("Armor Mod")
  expect(cardData[17].description).toBe("Increases reload speed of Sidearms.")
  expect(cardData[17].icon).toBe("https://bungie.net/common/destiny2_content/icons/4af8bade4eaef5ca1996d5a8e9c9e37d.png")
  expect(cardData[17].timesSold).toBe(3)
  expect(cardData[17].lastSold).toBe("2021-03-20")
  expect(cardData[18].name).toBe("Icarus Grip")
  expect(cardData[18].type).toBe("Weapon Mod")
  expect(cardData[18].description).toBe("Improves accuracy while airborne.")
  expect(cardData[18].icon).toBe("https://bungie.net/common/destiny2_content/icons/87283ef665c15177108da57f33551a3b.jpg")
  expect(cardData[18].timesSold).toBe(33)
  expect(cardData[18].lastSold).toBe("2021-03-19")
  expect(cardData[19].name).toBe("Unflinching Grenade Launcher Aim")
  expect(cardData[19].type).toBe("Armor Mod")
  expect(cardData[19].description).toBe("Reduces flinching from incoming fire while aiming Grenade Launchers.")
  expect(cardData[19].icon).toBe("https://bungie.net/common/destiny2_content/icons/dfa35fc69b72b504adc0e86e0a7434ff.png")
  expect(cardData[19].timesSold).toBe(2)
  expect(cardData[19].lastSold).toBe("2021-03-19")
  expect(cardData[20].name).toBe("Sheltering Energy")
  expect(cardData[20].type).toBe("Warmind Cell Mod")
  expect(cardData[20].description).toBe("Collecting a Warmind Cell grants you an overshield.")
  expect(cardData[20].icon).toBe("https://bungie.net/common/destiny2_content/icons/7e6816b6da94913a9743d2855191ee88.png")
  expect(cardData[20].timesSold).toBe(2)
  expect(cardData[20].lastSold).toBe("2021-03-18")
  expect(cardData[21].name).toBe("Sniper Rifle Scavenger")
  expect(cardData[21].type).toBe("Armor Mod")
  expect(cardData[21].description).toBe("Sniper Rifles get bonus reserves when you pick up Special ammo.")
  expect(cardData[21].icon).toBe("https://bungie.net/common/destiny2_content/icons/3703c9e60783d6aba0a259976a9481d7.png")
  expect(cardData[21].timesSold).toBe(2)
  expect(cardData[21].lastSold).toBe("2021-03-17")
  expect(cardData[22].name).toBe("Incinerating Light")
  expect(cardData[22].type).toBe("Warmind Cell Mod")
  expect(cardData[22].description).toBe("Become Charged with Light by rapidly defeating multiple enemies with the explosion of a Warmind Cell.")
  expect(cardData[22].icon).toBe("https://bungie.net/common/destiny2_content/icons/14dc085823df3d8819aedad8747bc09c.png")
  expect(cardData[22].timesSold).toBe(2)
  expect(cardData[22].lastSold).toBe("2021-03-16")
  expect(cardData[23].name).toBe("Unflinching Machine Gun")
  expect(cardData[23].type).toBe("Armor Mod")
  expect(cardData[23].description).toBe("Reduces hit flinch from incoming fire while aiming Machine Guns.")
  expect(cardData[23].icon).toBe("https://bungie.net/common/destiny2_content/icons/f91b08d440a599e8b69008ced64b5181.png")
  expect(cardData[23].timesSold).toBe(3)
  expect(cardData[23].lastSold).toBe("2021-03-15")
  expect(cardData[24].name).toBe("Burning Cells")
  expect(cardData[24].type).toBe("Warmind Cell Mod")
  expect(cardData[24].description).toBe("Destroying a Warmind Cell creates a burst of Solar energy that causes enemies to burn for several seconds.")
  expect(cardData[24].icon).toBe("https://bungie.net/common/destiny2_content/icons/e51fc35efbfb77746846ff39157de297.png")
  expect(cardData[24].timesSold).toBe(2)
  expect(cardData[24].lastSold).toBe("2021-03-14")
  expect(cardData[25].name).toBe("Boss Spec")
  expect(cardData[25].type).toBe("Weapon Mod")
  expect(cardData[25].description).toBe("Increases damage against bosses and vehicles.")
  expect(cardData[25].icon).toBe("https://bungie.net/common/destiny2_content/icons/fad820780bbac2625070353769c628ef.jpg")
  expect(cardData[25].timesSold).toBe(25)
  expect(cardData[25].lastSold).toBe("2021-03-13")
  expect(cardData[26].name).toBe("Counterbalance Stock")
  expect(cardData[26].type).toBe("Weapon Mod")
  expect(cardData[26].description).toBe("Reduces recoil deviation for the weapon.")
  expect(cardData[26].icon).toBe("https://bungie.net/common/destiny2_content/icons/c537bdf090f114963cce60636c98d7c2.jpg")
  expect(cardData[26].timesSold).toBe(38)
  expect(cardData[26].lastSold).toBe("2021-03-12")
  expect(cardData[27].name).toBe("Unflinching Sniper Aim")
  expect(cardData[27].type).toBe("Armor Mod")
  expect(cardData[27].description).toBe("Reduces flinching from incoming fire while aiming Sniper Rifles.")
  expect(cardData[27].icon).toBe("https://bungie.net/common/destiny2_content/icons/e104d516992ecdde609034141b851b26.png")
  expect(cardData[27].timesSold).toBe(8)
  expect(cardData[27].lastSold).toBe("2021-03-12")
  expect(cardData[28].name).toBe("Major Spec")
  expect(cardData[28].type).toBe("Weapon Mod")
  expect(cardData[28].description).toBe("Deals extra damage against powerful enemies.")
  expect(cardData[28].icon).toBe("https://bungie.net/common/destiny2_content/icons/4e3573080845b4ee9efcb000d4924cb0.jpg")
  expect(cardData[28].timesSold).toBe(35)
  expect(cardData[28].lastSold).toBe("2021-03-11")
  expect(cardData[29].name).toBe("Precision Charge")
  expect(cardData[29].type).toBe("Charged with Light Mod")
  expect(cardData[29].description).toBe("Become Charged with Light by rapidly defeating combatants with precision kills from Bows, Hand Cannons, and Scout Rifles.")
  expect(cardData[29].icon).toBe("https://bungie.net/common/destiny2_content/icons/2614935a04f326038bddff44a374e996.png")
  expect(cardData[29].timesSold).toBe(1)
  expect(cardData[29].lastSold).toBe("2021-03-11")
  expect(cardData[30].name).toBe("Submachine Gun Scavenger")
  expect(cardData[30].type).toBe("Armor Mod")
  expect(cardData[30].description).toBe("Submachine Guns get bonus reserves when you pick up ammo.")
  expect(cardData[30].icon).toBe("https://bungie.net/common/destiny2_content/icons/3a22e8fd59f16d52f478dff58d5f0909.png")
  expect(cardData[30].timesSold).toBe(1)
  expect(cardData[30].lastSold).toBe("2021-03-10")
  expect(cardData[31].name).toBe("Rocket Launcher Reserves")
  expect(cardData[31].type).toBe("Armor Mod")
  expect(cardData[31].description).toBe("Increases the amount of Rocket Launcher ammo you can carry.")
  expect(cardData[31].icon).toBe("https://bungie.net/common/destiny2_content/icons/998bbff08fca8d244b74d6236109f855.png")
  expect(cardData[31].timesSold).toBe(3)
  expect(cardData[31].lastSold).toBe("2021-03-09")
  expect(cardData[32].name).toBe("Radar Tuner")
  expect(cardData[32].type).toBe("Weapon Mod")
  expect(cardData[32].description).toBe("Radar immediately returns when you stop aiming down sights.")
  expect(cardData[32].icon).toBe("https://bungie.net/common/destiny2_content/icons/c0f1d2d9d818cee5c740fa6123730b54.jpg")
  expect(cardData[32].timesSold).toBe(25)
  expect(cardData[32].lastSold).toBe("2021-03-08")
  expect(cardData[33].name).toBe("Sidearm Targeting")
  expect(cardData[33].type).toBe("Armor Mod")
  expect(cardData[33].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Sidearms.")
  expect(cardData[33].icon).toBe("https://bungie.net/common/destiny2_content/icons/dcf93341f610a12e2e920310a4b5a64a.png")
  expect(cardData[33].timesSold).toBe(4)
  expect(cardData[33].lastSold).toBe("2021-03-08")
  expect(cardData[34].name).toBe("Warmind's Protection")
  expect(cardData[34].type).toBe("Warmind Cell Mod")
  expect(cardData[34].description).toBe("You take reduced damage from enemies that are near Warmind Cells.")
  expect(cardData[34].icon).toBe("https://bungie.net/common/destiny2_content/icons/9b3809c858edb260cdc2ae341c26601e.png")
  expect(cardData[34].timesSold).toBe(2)
  expect(cardData[34].lastSold).toBe("2021-03-07")
  expect(cardData[35].name).toBe("Minor Spec")
  expect(cardData[35].type).toBe("Weapon Mod")
  expect(cardData[35].description).toBe("Deals extra damage against rank-and-file enemies.")
  expect(cardData[35].icon).toBe("https://bungie.net/common/destiny2_content/icons/02c21091a41663aeaff7e26ab233bc20.jpg")
  expect(cardData[35].timesSold).toBe(40)
  expect(cardData[35].lastSold).toBe("2021-03-06")
  expect(cardData[36].name).toBe("Auto Rifle Targeting")
  expect(cardData[36].type).toBe("Armor Mod")
  expect(cardData[36].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Auto Rifles and Trace Rifles.")
  expect(cardData[36].icon).toBe("https://bungie.net/common/destiny2_content/icons/90a37644be43a6be4c0bfd5da2bf8f42.png")
  expect(cardData[36].timesSold).toBe(3)
  expect(cardData[36].lastSold).toBe("2021-03-06")
  expect(cardData[37].name).toBe("Sidearm Dexterity")
  expect(cardData[37].type).toBe("Armor Mod")
  expect(cardData[37].description).toBe("Faster ready and stow speed for Sidearms.")
  expect(cardData[37].icon).toBe("https://bungie.net/common/destiny2_content/icons/20198ffe9c9a86f29db2683f9284691b.png")
  expect(cardData[37].timesSold).toBe(5)
  expect(cardData[37].lastSold).toBe("2021-03-05")
  expect(cardData[38].name).toBe("Grenade Launcher Reserves")
  expect(cardData[38].type).toBe("Armor Mod")
  expect(cardData[38].description).toBe("Increases the amount of Grenade Launcher ammo you can carry.")
  expect(cardData[38].icon).toBe("https://bungie.net/common/destiny2_content/icons/eda11a352c552d800316e11c6b0bd112.png")
  expect(cardData[38].timesSold).toBe(5)
  expect(cardData[38].lastSold).toBe("2021-03-03")
  expect(cardData[39].name).toBe("Rocket Launcher Dexterity")
  expect(cardData[39].type).toBe("Armor Mod")
  expect(cardData[39].description).toBe("Faster ready and stow speed for Rocket Launchers.")
  expect(cardData[39].icon).toBe("https://bungie.net/common/destiny2_content/icons/8b8461ea49aa2ee1c50cc8e62a7e3b23.png")
  expect(cardData[39].timesSold).toBe(1)
  expect(cardData[39].lastSold).toBe("2021-03-02")
  expect(cardData[40].name).toBe("Submachine Gun Ammo Finder")
  expect(cardData[40].type).toBe("Armor Mod")
  expect(cardData[40].description).toBe("Increases your chance of finding Primary ammo while you have a Submachine Gun equipped.")
  expect(cardData[40].icon).toBe("https://bungie.net/common/destiny2_content/icons/252398e0e2e61785c2d0d874b571a02c.png")
  expect(cardData[40].timesSold).toBe(1)
  expect(cardData[40].lastSold).toBe("2021-02-28")
  expect(cardData[41].name).toBe("Sidearm Ammo Finder")
  expect(cardData[41].type).toBe("Armor Mod")
  expect(cardData[41].description).toBe("Increases your chance of finding Primary ammo while you have a Sidearm equipped.")
  expect(cardData[41].icon).toBe("https://bungie.net/common/destiny2_content/icons/c1ae38920a60c4e8f393d44761972169.png")
  expect(cardData[41].timesSold).toBe(3)
  expect(cardData[41].lastSold).toBe("2021-02-27")
  expect(cardData[42].name).toBe("Extra Reserves")
  expect(cardData[42].type).toBe("Charged with Light Mod")
  expect(cardData[42].description).toBe("While Charged with Light, defeating combatants with Void damage grants a chance to drop Special ammo. This effect consumes all stacks of Charged with Light. The more stacks you have, the higher your chance of gaining the ammo drop.")
  expect(cardData[42].icon).toBe("https://bungie.net/common/destiny2_content/icons/fc70edeb4ce73caf4021b67c0017794b.png")
  expect(cardData[42].timesSold).toBe(3)
  expect(cardData[42].lastSold).toBe("2021-02-26")
  expect(cardData[43].name).toBe("Sword Ammo Finder")
  expect(cardData[43].type).toBe("Armor Mod")
  expect(cardData[43].description).toBe("Increases your chance of finding Heavy ammo while you have a Sword equipped.")
  expect(cardData[43].icon).toBe("https://bungie.net/common/destiny2_content/icons/3f9257833e7868adb737570612db3fe8.png")
  expect(cardData[43].timesSold).toBe(2)
  expect(cardData[43].lastSold).toBe("2021-02-25")
  expect(cardData[44].name).toBe("Submachine Gun Dexterity")
  expect(cardData[44].type).toBe("Armor Mod")
  expect(cardData[44].description).toBe("Faster ready and stow speed for Submachine Guns.")
  expect(cardData[44].icon).toBe("https://bungie.net/common/destiny2_content/icons/ea0baac685d7becb74ba30a5e00ee3d7.png")
  expect(cardData[44].timesSold).toBe(3)
  expect(cardData[44].lastSold).toBe("2021-02-24")
  expect(cardData[45].name).toBe("Fusion Rifle Reserves")
  expect(cardData[45].type).toBe("Armor Mod")
  expect(cardData[45].description).toBe("Increases the amount of Fusion Rifle ammo you can carry.")
  expect(cardData[45].icon).toBe("https://bungie.net/common/destiny2_content/icons/b79414f7866e5e2f307871acfbe86238.png")
  expect(cardData[45].timesSold).toBe(4)
  expect(cardData[45].lastSold).toBe("2021-02-23")
  expect(cardData[46].name).toBe("Fusion Rifle Scavenger")
  expect(cardData[46].type).toBe("Armor Mod")
  expect(cardData[46].description).toBe("Fusion Rifles get bonus reserves when you pick up Special ammo.")
  expect(cardData[46].icon).toBe("https://bungie.net/common/destiny2_content/icons/692521d0d7d3a4432f98773d484c3f9a.png")
  expect(cardData[46].timesSold).toBe(5)
  expect(cardData[46].lastSold).toBe("2021-02-22")
  expect(cardData[47].name).toBe("Strength of Rasputin")
  expect(cardData[47].type).toBe("Warmind Cell Mod")
  expect(cardData[47].description).toBe("Collecting a Warmind Cell grants you melee energy.")
  expect(cardData[47].icon).toBe("https://bungie.net/common/destiny2_content/icons/20a81ffdf748de8cebd8c90973a5275e.png")
  expect(cardData[47].timesSold).toBe(3)
  expect(cardData[47].lastSold).toBe("2021-02-21")
  expect(cardData[48].name).toBe("Unflinching Fusion Rifle Aim")
  expect(cardData[48].type).toBe("Armor Mod")
  expect(cardData[48].description).toBe("Reduces flinching from incoming fire while aiming Fusion Rifles.")
  expect(cardData[48].icon).toBe("https://bungie.net/common/destiny2_content/icons/eb5f2e47bc787d8d7a8109b362f0e61c.png")
  expect(cardData[48].timesSold).toBe(2)
  expect(cardData[48].lastSold).toBe("2021-02-20")
  expect(cardData[49].name).toBe("Sustained Charge")
  expect(cardData[49].type).toBe("Charged with Light Mod")
  expect(cardData[49].description).toBe("Become Charged with Light by rapidly defeating combatants with Auto Rifles, Trace Rifles, or Machine Guns. Additional copies of this mod increase the time allowed between combatants that are defeated.")
  expect(cardData[49].icon).toBe("https://bungie.net/common/destiny2_content/icons/900534ac5f6ffd274521ed7fc0e43e31.png")
  expect(cardData[49].timesSold).toBe(2)
  expect(cardData[49].lastSold).toBe("2021-02-19")
  expect(cardData[50].name).toBe("Hand Cannon Targeting")
  expect(cardData[50].type).toBe("Armor Mod")
  expect(cardData[50].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Hand Cannons.")
  expect(cardData[50].icon).toBe("https://bungie.net/common/destiny2_content/icons/24b5e0c0687d15f596472c2c73b49517.png")
  expect(cardData[50].timesSold).toBe(1)
  expect(cardData[50].lastSold).toBe("2021-02-18")
  expect(cardData[51].name).toBe("Surrounded Spec")
  expect(cardData[51].type).toBe("Weapon Mod")
  expect(cardData[51].description).toBe("Increases the damage granted by Surrounded. Bonus damage lingers for a brief time when no longer surrounded by three or more enemies.")
  expect(cardData[51].icon).toBe("https://bungie.net/common/destiny2_content/icons/077fe0d989557b5c9f62c8f9f8bca9ed.jpg")
  expect(cardData[51].timesSold).toBe(6)
  expect(cardData[51].lastSold).toBe("2021-02-17")
  expect(cardData[52].name).toBe("Bow Reloader")
  expect(cardData[52].type).toBe("Armor Mod")
  expect(cardData[52].description).toBe("Increases the nocking speed of arrows.")
  expect(cardData[52].icon).toBe("https://bungie.net/common/destiny2_content/icons/47df7780b705e2fc829ba28114e652c3.png")
  expect(cardData[52].timesSold).toBe(3)
  expect(cardData[52].lastSold).toBe("2021-02-17")
  expect(cardData[53].name).toBe("Sniper Rifle Reserves")
  expect(cardData[53].type).toBe("Armor Mod")
  expect(cardData[53].description).toBe("Increases the amount of Sniper Rifle ammo you can carry.")
  expect(cardData[53].icon).toBe("https://bungie.net/common/destiny2_content/icons/8700b5f6f2a832d513f81746d796f439.png")
  expect(cardData[53].timesSold).toBe(3)
  expect(cardData[53].lastSold).toBe("2021-02-15")
  expect(cardData[54].name).toBe("Pulse Rifle Dexterity")
  expect(cardData[54].type).toBe("Armor Mod")
  expect(cardData[54].description).toBe("Faster ready and stow speed for Pulse Rifles.")
  expect(cardData[54].icon).toBe("https://bungie.net/common/destiny2_content/icons/fed35822cf04a8405492211ad2bba2a0.png")
  expect(cardData[54].timesSold).toBe(3)
  expect(cardData[54].lastSold).toBe("2021-02-14")
  expect(cardData[55].name).toBe("Scout Rifle Ammo Finder")
  expect(cardData[55].type).toBe("Armor Mod")
  expect(cardData[55].description).toBe("Increases your chance of finding Primary ammo while you have a Scout Rifle equipped.")
  expect(cardData[55].icon).toBe("https://bungie.net/common/destiny2_content/icons/4b6172cfd0693a109f09f868ba3bcc26.png")
  expect(cardData[55].timesSold).toBe(3)
  expect(cardData[55].lastSold).toBe("2021-02-13")
  expect(cardData[56].name).toBe("Charge Harvester")
  expect(cardData[56].type).toBe("Charged with Light Mod")
  expect(cardData[56].description).toBe("While you are not Charged with Light, any kill or assist has a small cumulative chance to cause you to become Charged with Light.")
  expect(cardData[56].icon).toBe("https://bungie.net/common/destiny2_content/icons/a8acc2b6cf36527f879051a38622e310.png")
  expect(cardData[56].timesSold).toBe(1)
  expect(cardData[56].lastSold).toBe("2021-02-12")
  expect(cardData[57].name).toBe("Bow Ammo Finder")
  expect(cardData[57].type).toBe("Armor Mod")
  expect(cardData[57].description).toBe("Increases your chance of finding Primary ammo while you have a Bow equipped.")
  expect(cardData[57].icon).toBe("https://bungie.net/common/destiny2_content/icons/4f7b531fac3f1311e4b7847874f3d949.png")
  expect(cardData[57].timesSold).toBe(1)
  expect(cardData[57].lastSold).toBe("2021-02-11")
  expect(cardData[58].name).toBe("Unflinching Scout Rifle Aim")
  expect(cardData[58].type).toBe("Armor Mod")
  expect(cardData[58].description).toBe("Reduces flinching from incoming fire while aiming Scout Rifles.")
  expect(cardData[58].icon).toBe("https://bungie.net/common/destiny2_content/icons/84f799f6a73473be939afc549b18d669.png")
  expect(cardData[58].timesSold).toBe(2)
  expect(cardData[58].lastSold).toBe("2021-02-10")
  expect(cardData[59].name).toBe("Hand Cannon Ammo Finder")
  expect(cardData[59].type).toBe("Armor Mod")
  expect(cardData[59].description).toBe("Increases your chance of finding Primary ammo while you have a Hand Cannon equipped.")
  expect(cardData[59].icon).toBe("https://bungie.net/common/destiny2_content/icons/4c0ad0185e173ccc3eec62854639d9d9.png")
  expect(cardData[59].timesSold).toBe(1)
  expect(cardData[59].lastSold).toBe("2021-02-09")
  expect(cardData[60].name).toBe("Linear Fusion Rifle Targeting")
  expect(cardData[60].type).toBe("Armor Mod")
  expect(cardData[60].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Linear Fusion Rifles.")
  expect(cardData[60].icon).toBe("https://bungie.net/common/destiny2_content/icons/0b0ee64a72b55e981bc3f7259ac2d590.png")
  expect(cardData[60].timesSold).toBe(4)
  expect(cardData[60].lastSold).toBe("2021-02-07")
  expect(cardData[61].name).toBe("Auto Rifle Ammo Finder")
  expect(cardData[61].type).toBe("Armor Mod")
  expect(cardData[61].description).toBe("Increases your chance of finding Primary ammo while you have an Auto Rifle equipped.")
  expect(cardData[61].icon).toBe("https://bungie.net/common/destiny2_content/icons/dc37c24803941961339e59e92d611033.png")
  expect(cardData[61].timesSold).toBe(3)
  expect(cardData[61].lastSold).toBe("2021-02-04")
  expect(cardData[62].name).toBe("Submachine Gun Loader")
  expect(cardData[62].type).toBe("Armor Mod")
  expect(cardData[62].description).toBe("Increases reload speed of Submachine Guns.")
  expect(cardData[62].icon).toBe("https://bungie.net/common/destiny2_content/icons/0cf177981705d5633f9ace696c4d9f39.png")
  expect(cardData[62].timesSold).toBe(2)
  expect(cardData[62].lastSold).toBe("2021-02-01")
  expect(cardData[63].name).toBe("Heal Thyself")
  expect(cardData[63].type).toBe("Charged with Light Mod")
  expect(cardData[63].description).toBe("While you are Charged with Light, grenade final blows heal you and consume one stack of Charged with Light.")
  expect(cardData[63].icon).toBe("https://bungie.net/common/destiny2_content/icons/e7067bd91843c6a9a40cceba9d376683.png")
  expect(cardData[63].timesSold).toBe(2)
  expect(cardData[63].lastSold).toBe("2021-01-31")
  expect(cardData[64].name).toBe("Sidearm Scavenger")
  expect(cardData[64].type).toBe("Armor Mod")
  expect(cardData[64].description).toBe("Sidearms get bonus reserves when you pick up ammo.")
  expect(cardData[64].icon).toBe("https://bungie.net/common/destiny2_content/icons/b60763f81889eaf07329eaf32b01b0ae.png")
  expect(cardData[64].timesSold).toBe(3)
  expect(cardData[64].lastSold).toBe("2021-01-30")
  expect(cardData[65].name).toBe("Rocket Launcher Scavenger")
  expect(cardData[65].type).toBe("Armor Mod")
  expect(cardData[65].description).toBe("Rocket Launchers get bonus reserves when you pick up ammo.")
  expect(cardData[65].icon).toBe("https://bungie.net/common/destiny2_content/icons/9e7860f02150e019b059b2e104a32b97.png")
  expect(cardData[65].timesSold).toBe(4)
  expect(cardData[65].lastSold).toBe("2021-01-29")
  expect(cardData[66].name).toBe("Energy Converter")
  expect(cardData[66].type).toBe("Charged with Light Mod")
  expect(cardData[66].description).toBe("While Charged with Light, using your grenade attack grants you Super energy, consuming all stacks of Charged with Light. The more stacks you have, the more energy you gain, up to a maximum of 50% of your Super energy.")
  expect(cardData[66].icon).toBe("https://bungie.net/common/destiny2_content/icons/e0b2cb5c2a1fd8ffa92f20c91ed5e7e0.png")
  expect(cardData[66].timesSold).toBe(1)
  expect(cardData[66].lastSold).toBe("2021-01-28")
  expect(cardData[67].name).toBe("Blessing of Rasputin")
  expect(cardData[67].type).toBe("Warmind Cell Mod")
  expect(cardData[67].description).toBe("Collecting a Warmind Cell increases the chances that your next final blow with a Seraph weapon will create a Warmind Cell.")
  expect(cardData[67].icon).toBe("https://bungie.net/common/destiny2_content/icons/3b89677660624c4c0bd27e89fe52649c.png")
  expect(cardData[67].timesSold).toBe(2)
  expect(cardData[67].lastSold).toBe("2021-01-27")
  expect(cardData[68].name).toBe("Pulse Rifle Loader")
  expect(cardData[68].type).toBe("Armor Mod")
  expect(cardData[68].description).toBe("Increases reload speed of Pulse Rifles.")
  expect(cardData[68].icon).toBe("https://bungie.net/common/destiny2_content/icons/321b9bacddce27d2d4c661ddbe7d203c.png")
  expect(cardData[68].timesSold).toBe(3)
  expect(cardData[68].lastSold).toBe("2021-01-25")
  expect(cardData[69].name).toBe("Grenade Launcher Scavenger")
  expect(cardData[69].type).toBe("Armor Mod")
  expect(cardData[69].description).toBe("Grenade Launchers get bonus reserves when you pick up ammo.")
  expect(cardData[69].icon).toBe("https://bungie.net/common/destiny2_content/icons/b6151afb1922d7b55184f5a2e2ff0ebb.png")
  expect(cardData[69].timesSold).toBe(4)
  expect(cardData[69].lastSold).toBe("2021-01-24")
  expect(cardData[70].name).toBe("Grasp of the Warmind")
  expect(cardData[70].type).toBe("Warmind Cell Mod")
  expect(cardData[70].description).toBe("You can pick up, carry, and throw Warmind Cells. Once thrown, a Warmind Cell cannot be picked up again.")
  expect(cardData[70].icon).toBe("https://bungie.net/common/destiny2_content/icons/180ee0e9b32d2676a171dfbc606b14ba.png")
  expect(cardData[70].timesSold).toBe(2)
  expect(cardData[70].lastSold).toBe("2021-01-22")
  expect(cardData[71].name).toBe("Auto Rifle Scavenger")
  expect(cardData[71].type).toBe("Armor Mod")
  expect(cardData[71].description).toBe("Auto Rifles get bonus reserves when you pick up ammo.")
  expect(cardData[71].icon).toBe("https://bungie.net/common/destiny2_content/icons/5a8063288c58c6d329cd66fffde4e350.png")
  expect(cardData[71].timesSold).toBe(3)
  expect(cardData[71].lastSold).toBe("2021-01-21")
  expect(cardData[72].name).toBe("Submachine Gun Targeting")
  expect(cardData[72].type).toBe("Armor Mod")
  expect(cardData[72].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Submachine Guns.")
  expect(cardData[72].icon).toBe("https://bungie.net/common/destiny2_content/icons/73c7b20dacf59b2e2bb460184f22c11d.png")
  expect(cardData[72].timesSold).toBe(4)
  expect(cardData[72].lastSold).toBe("2021-01-20")
  expect(cardData[73].name).toBe("Hand Cannon Loader")
  expect(cardData[73].type).toBe("Armor Mod")
  expect(cardData[73].description).toBe("Increases reload speed of Hand Cannons.")
  expect(cardData[73].icon).toBe("https://bungie.net/common/destiny2_content/icons/aea4a74a51ddbed77350afdafaaf13cd.png")
  expect(cardData[73].timesSold).toBe(4)
  expect(cardData[73].lastSold).toBe("2021-01-17")
  expect(cardData[74].name).toBe("Swift Charge")
  expect(cardData[74].type).toBe("Charged with Light Mod")
  expect(cardData[74].description).toBe("Become Charged with Light by rapidly defeating combatants with Pulse Rifles, Sidearms, or Submachine Guns.")
  expect(cardData[74].icon).toBe("https://bungie.net/common/destiny2_content/icons/80b1179638c3627864a1ab5247151305.png")
  expect(cardData[74].timesSold).toBe(1)
  expect(cardData[74].lastSold).toBe("2021-01-16")
  expect(cardData[75].name).toBe("Machine Gun Targeting")
  expect(cardData[75].type).toBe("Armor Mod")
  expect(cardData[75].description).toBe("Improved target acquisition, accuracy, and aim down sights speed for Machine Guns.")
  expect(cardData[75].icon).toBe("https://bungie.net/common/destiny2_content/icons/8ebb9612f54977cd2a6f0d3d67f1a6f2.png")
  expect(cardData[75].timesSold).toBe(2)
  expect(cardData[75].lastSold).toBe("2021-01-15")
  expect(cardData[76].name).toBe("Machine Gun Reserves")
  expect(cardData[76].type).toBe("Armor Mod")
  expect(cardData[76].description).toBe("Increase the amount of Machine Gun ammo you can carry.")
  expect(cardData[76].icon).toBe("https://bungie.net/common/destiny2_content/icons/cee338f4c63ce1e8abb40bdee6d239ef.png")
  expect(cardData[76].timesSold).toBe(2)
  expect(cardData[76].lastSold).toBe("2021-01-14")
  expect(cardData[77].name).toBe("Unflinching Submachine Gun Aim")
  expect(cardData[77].type).toBe("Armor Mod")
  expect(cardData[77].description).toBe("Reduces flinching from incoming fire while aiming Submachine Guns.")
  expect(cardData[77].icon).toBe("https://bungie.net/common/destiny2_content/icons/09dc11384483de48bfca39d3b48f9298.png")
  expect(cardData[77].timesSold).toBe(6)
  expect(cardData[77].lastSold).toBe("2021-01-12")
  expect(cardData[78].name).toBe("Bow Reserves")
  expect(cardData[78].type).toBe("Armor Mod")
  expect(cardData[78].description).toBe("Increases the amount of Bow ammo you can carry.")
  expect(cardData[78].icon).toBe("https://bungie.net/common/destiny2_content/icons/b28e4384a52a150b81ee70282c7a93a9.png")
  expect(cardData[78].timesSold).toBe(4)
  expect(cardData[78].lastSold).toBe("2021-01-11")
  expect(cardData[79].name).toBe("Light from Darkness")
  expect(cardData[79].type).toBe("Warmind Cell Mod")
  expect(cardData[79].description).toBe("Become Charged with Light by rapidly defeating multiple enemies near a Warmind Cell using weapons or abilities.")
  expect(cardData[79].icon).toBe("https://bungie.net/common/destiny2_content/icons/14dc085823df3d8819aedad8747bc09c.png")
  expect(cardData[79].timesSold).toBe(1)
  expect(cardData[79].lastSold).toBe("2021-01-09")
  expect(cardData[80].name).toBe("Grenade Launcher Loader")
  expect(cardData[80].type).toBe("Armor Mod")
  expect(cardData[80].description).toBe("Increases reload speed of Grenade Launchers.")
  expect(cardData[80].icon).toBe("https://bungie.net/common/destiny2_content/icons/631e8f886cd0eda3f2debb7cfbbb203d.png")
  expect(cardData[80].timesSold).toBe(3)
  expect(cardData[80].lastSold).toBe("2021-01-08")
  expect(cardData[81].name).toBe("Sniper Rifle Targeting")
  expect(cardData[81].type).toBe("Armor Mod")
  expect(cardData[81].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Sniper Rifles.")
  expect(cardData[81].icon).toBe("https://bungie.net/common/destiny2_content/icons/9aee84e9176a73dc541bc34629e0a233.png")
  expect(cardData[81].timesSold).toBe(4)
  expect(cardData[81].lastSold).toBe("2021-01-06")
  expect(cardData[82].name).toBe("Kindling the Flame")
  expect(cardData[82].type).toBe("Charged with Light Mod")
  expect(cardData[82].description).toBe("While Charged with Light, reviving a downed Guardian gives you a burst of healing, consuming one stack of Charged with Light.")
  expect(cardData[82].icon).toBe("https://bungie.net/common/destiny2_content/icons/cc1eb304baed451cbb4b8b5cfcab164f.png")
  expect(cardData[82].timesSold).toBe(2)
  expect(cardData[82].lastSold).toBe("2021-01-05")
  expect(cardData[83].name).toBe("Chosen of the Warmind")
  expect(cardData[83].type).toBe("Warmind Cell Mod")
  expect(cardData[83].description).toBe("Collecting or destroying a Warmind Cell creates a concussive blast that pushes enemies away.")
  expect(cardData[83].icon).toBe("https://bungie.net/common/destiny2_content/icons/0d11c3a259eb95eb3918bd2130b304ac.png")
  expect(cardData[83].timesSold).toBe(4)
  expect(cardData[83].lastSold).toBe("2021-01-03")
  expect(cardData[84].name).toBe("Unflinching Linear Fusion Aim")
  expect(cardData[84].type).toBe("Armor Mod")
  expect(cardData[84].description).toBe("Reduces flinching from incoming fire while aiming Linear Fusion Rifles.")
  expect(cardData[84].icon).toBe("https://bungie.net/common/destiny2_content/icons/af8c3f7f19d4e141bd58c53310826da2.png")
  expect(cardData[84].timesSold).toBe(7)
  expect(cardData[84].lastSold).toBe("2021-01-02")
  expect(cardData[85].name).toBe("Sniper Rifle Dexterity")
  expect(cardData[85].type).toBe("Armor Mod")
  expect(cardData[85].description).toBe("Faster ready and stow speed for Sniper Rifles.")
  expect(cardData[85].icon).toBe("https://bungie.net/common/destiny2_content/icons/b25e9791a5a0ef4b99279135098f9469.png")
  expect(cardData[85].timesSold).toBe(2)
  expect(cardData[85].lastSold).toBe("2021-01-01")
  expect(cardData[86].name).toBe("Fusion Rifle Dexterity")
  expect(cardData[86].type).toBe("Armor Mod")
  expect(cardData[86].description).toBe("Faster ready and stow speed for Fusion Rifles.")
  expect(cardData[86].icon).toBe("https://bungie.net/common/destiny2_content/icons/f0b919dbe17cdfa7aa4df1e35ef32650.png")
  expect(cardData[86].timesSold).toBe(4)
  expect(cardData[86].lastSold).toBe("2020-12-31")
  expect(cardData[87].name).toBe("Auto Rifle Loader")
  expect(cardData[87].type).toBe("Armor Mod")
  expect(cardData[87].description).toBe("Increases reload speed of Auto Rifles and Trace Rifles.")
  expect(cardData[87].icon).toBe("https://bungie.net/common/destiny2_content/icons/b347afa5ea1de90d71a19befad378e5a.png")
  expect(cardData[87].timesSold).toBe(2)
  expect(cardData[87].lastSold).toBe("2020-12-30")
  expect(cardData[88].name).toBe("Power of Rasputin")
  expect(cardData[88].type).toBe("Warmind Cell Mod")
  expect(cardData[88].description).toBe("You gain a bonus to weapon damage against enemies that are near Warmind Cells.")
  expect(cardData[88].icon).toBe("https://bungie.net/common/destiny2_content/icons/75029cbc3eb965029197391d41ff9246.png")
  expect(cardData[88].timesSold).toBe(2)
  expect(cardData[88].lastSold).toBe("2020-12-29")
  expect(cardData[89].name).toBe("Pulse Rifle Scavenger")
  expect(cardData[89].type).toBe("Armor Mod")
  expect(cardData[89].description).toBe("Pulse Rifles get bonus reserves when you pick up ammo.")
  expect(cardData[89].icon).toBe("https://bungie.net/common/destiny2_content/icons/fa7d46d48a28cf008ca556648dbd17e8.png")
  expect(cardData[89].timesSold).toBe(4)
  expect(cardData[89].lastSold).toBe("2020-12-28")
  expect(cardData[90].name).toBe("Charged Up")
  expect(cardData[90].type).toBe("Charged with Light Mod")
  expect(cardData[90].description).toBe("Allows for 1 additional stack of Charged with Light.")
  expect(cardData[90].icon).toBe("https://bungie.net/common/destiny2_content/icons/ce29f32ba5ef8758d1b5f3cfad0944a6.png")
  expect(cardData[90].timesSold).toBe(3)
  expect(cardData[90].lastSold).toBe("2020-12-24")
  expect(cardData[91].name).toBe("Fusion Rifle Loader")
  expect(cardData[91].type).toBe("Armor Mod")
  expect(cardData[91].description).toBe("Increases reload speed of Fusion Rifles.")
  expect(cardData[91].icon).toBe("https://bungie.net/common/destiny2_content/icons/4bd5d235727b184427cdd0b79036d6d7.png")
  expect(cardData[91].timesSold).toBe(3)
  expect(cardData[91].lastSold).toBe("2020-12-23")
  expect(cardData[92].name).toBe("Arrow Scavenger")
  expect(cardData[92].type).toBe("Armor Mod")
  expect(cardData[92].description).toBe("Bows get bonus reserves when you pick up ammo.")
  expect(cardData[92].icon).toBe("https://bungie.net/common/destiny2_content/icons/10f2870c3bc0479befbeb198bdcf0e12.png")
  expect(cardData[92].timesSold).toBe(4)
  expect(cardData[92].lastSold).toBe("2020-12-22")
  expect(cardData[93].name).toBe("Machine Gun Loader")
  expect(cardData[93].type).toBe("Armor Mod")
  expect(cardData[93].description).toBe("Increases the reload speed of Machine Guns.")
  expect(cardData[93].icon).toBe("https://bungie.net/common/destiny2_content/icons/b980e2d7c665239655fa1fac7fc05faa.png")
  expect(cardData[93].timesSold).toBe(5)
  expect(cardData[93].lastSold).toBe("2020-12-18")
  expect(cardData[94].name).toBe("Pulse Rifle Ammo Finder")
  expect(cardData[94].type).toBe("Armor Mod")
  expect(cardData[94].description).toBe("Increases your chance of finding Primary ammo while you have a Pulse Rifle equipped.")
  expect(cardData[94].icon).toBe("https://bungie.net/common/destiny2_content/icons/24d9c875a756cc1bcd83985235fcff7c.png")
  expect(cardData[94].timesSold).toBe(4)
  expect(cardData[94].lastSold).toBe("2020-12-17")
  expect(cardData[95].name).toBe("Shotgun Dexterity")
  expect(cardData[95].type).toBe("Armor Mod")
  expect(cardData[95].description).toBe("Faster ready and stow speed for Shotguns.")
  expect(cardData[95].icon).toBe("https://bungie.net/common/destiny2_content/icons/289d94384604378342d0ba62fc11b4bb.png")
  expect(cardData[95].timesSold).toBe(5)
  expect(cardData[95].lastSold).toBe("2020-12-14")
  expect(cardData[96].name).toBe("Hand Cannon Dexterity")
  expect(cardData[96].type).toBe("Armor Mod")
  expect(cardData[96].description).toBe("Faster ready and stow speed for Hand Cannons.")
  expect(cardData[96].icon).toBe("https://bungie.net/common/destiny2_content/icons/bbf83c956ccae185a26b7d914739d9e4.png")
  expect(cardData[96].timesSold).toBe(2)
  expect(cardData[96].lastSold).toBe("2020-12-13")
  expect(cardData[97].name).toBe("Linear Fusion Dexterity")
  expect(cardData[97].type).toBe("Armor Mod")
  expect(cardData[97].description).toBe("Faster ready and stow speed for Linear Fusion Rifles.")
  expect(cardData[97].icon).toBe("https://bungie.net/common/destiny2_content/icons/25458636887e9eeff6868c6daaa6482c.png")
  expect(cardData[97].timesSold).toBe(2)
  expect(cardData[97].lastSold).toBe("2020-12-12")
  expect(cardData[98].name).toBe("Surprise Attack")
  expect(cardData[98].type).toBe("Charged with Light Mod")
  expect(cardData[98].description).toBe("While Charged with Light, reloading or readying a Sidearm will consume all stacks of Charged with Light and convert them into stacks of a major damage buff, which are depleted as you damage combatants with that Sidearm.")
  expect(cardData[98].icon).toBe("https://bungie.net/common/destiny2_content/icons/df471d6e132702ba8bdfc87b16d1c441.png")
  expect(cardData[98].timesSold).toBe(2)
  expect(cardData[98].lastSold).toBe("2020-12-11")
  expect(cardData[99].name).toBe("Warmind's Light")
  expect(cardData[99].type).toBe("Warmind Cell Mod")
  expect(cardData[99].description).toBe("Become Charged with Light by collecting a Warmind Cell.")
  expect(cardData[99].icon).toBe("https://bungie.net/common/destiny2_content/icons/14dc085823df3d8819aedad8747bc09c.png")
  expect(cardData[99].timesSold).toBe(2)
  expect(cardData[99].lastSold).toBe("2020-12-10")
  expect(cardData[100].name).toBe("Blast Radius")
  expect(cardData[100].type).toBe("Charged with Light Mod")
  expect(cardData[100].description).toBe("Become Charged with Light by rapidly defeating multiple combatants with Grenade Launchers or Rocket Launchers.")
  expect(cardData[100].icon).toBe("https://bungie.net/common/destiny2_content/icons/6b0d065905e6e640a2c23b1af25160d1.png")
  expect(cardData[100].timesSold).toBe(2)
  expect(cardData[100].lastSold).toBe("2020-12-09")
  expect(cardData[101].name).toBe("Striking Light")
  expect(cardData[101].type).toBe("Charged with Light Mod")
  expect(cardData[101].description).toBe("While Charged with Light, defeating combatants with melee damage and Swords spawns 1 Orb of Power for your allies and consumes one stack of Charged with Light.")
  expect(cardData[101].icon).toBe("https://bungie.net/common/destiny2_content/icons/e1eb7cf6ad88c3311f775df370bd21e4.png")
  expect(cardData[101].timesSold).toBe(3)
  expect(cardData[101].lastSold).toBe("2020-12-01")
  expect(cardData[102].name).toBe("Hand Cannon Reserves")
  expect(cardData[102].type).toBe("Armor Mod")
  expect(cardData[102].description).toBe("Increases the amount of Hand Cannon ammo you can carry.")
  expect(cardData[102].icon).toBe("https://bungie.net/common/destiny2_content/icons/245da97d50fecb936aab369db3cc0659.png")
  expect(cardData[102].timesSold).toBe(3)
  expect(cardData[102].lastSold).toBe("2020-11-30")
  expect(cardData[103].name).toBe("Lucent Blade")
  expect(cardData[103].type).toBe("Charged with Light Mod")
  expect(cardData[103].description).toBe("While Charged with Light, dealing damage with a Sword gives you bonus Sword damage for 5 seconds, consuming one stack of Charged with Light.")
  expect(cardData[103].icon).toBe("https://bungie.net/common/destiny2_content/icons/b2863d7ca41af5bca31641ecc6c5998a.png")
  expect(cardData[103].timesSold).toBe(1)
  expect(cardData[103].lastSold).toBe("2020-11-28")
  expect(cardData[104].name).toBe("Stacks on Stacks")
  expect(cardData[104].type).toBe("Charged with Light Mod")
  expect(cardData[104].description).toBe("Gain an extra stack of Charged with Light for every stack you gain.")
  expect(cardData[104].icon).toBe("https://bungie.net/common/destiny2_content/icons/519f5f15cddf0f17906e951fd3a9769b.png")
  expect(cardData[104].timesSold).toBe(3)
  expect(cardData[104].lastSold).toBe("2020-11-26")
  expect(cardData[105].name).toBe("Unflinching Hand Cannon Aim")
  expect(cardData[105].type).toBe("Armor Mod")
  expect(cardData[105].description).toBe("Reduces flinching from incoming fire while aiming Hand Cannons.")
  expect(cardData[105].icon).toBe("https://bungie.net/common/destiny2_content/icons/e42e42a3846155c12f00657dd4ab1581.png")
  expect(cardData[105].timesSold).toBe(3)
  expect(cardData[105].lastSold).toBe("2020-11-20")
  expect(cardData[106].name).toBe("Linear Fusion Rifle Loader")
  expect(cardData[106].type).toBe("Armor Mod")
  expect(cardData[106].description).toBe("Increases reload speed of Linear Fusion Rifles.")
  expect(cardData[106].icon).toBe("https://bungie.net/common/destiny2_content/icons/38827b292fc7d628409ac950b539602d.png")
  expect(cardData[106].timesSold).toBe(4)
  expect(cardData[106].lastSold).toBe("2020-11-19")
  expect(cardData[107].name).toBe("Protective Light")
  expect(cardData[107].type).toBe("Charged with Light Mod")
  expect(cardData[107].description).toBe("While Charged with Light, you gain significant damage resistance against combatants when your shields are destroyed. This effect consumes all stacks of Charged with Light. The more stacks consumed, the longer the damage resistance lasts.")
  expect(cardData[107].icon).toBe("https://bungie.net/common/destiny2_content/icons/f9d3dcc86e0805401b6f0ce72b0847ba.png")
  expect(cardData[107].timesSold).toBe(2)
  expect(cardData[107].lastSold).toBe("2020-11-18")
  expect(cardData[108].name).toBe("Linear Fusion Rifle Ammo Finder")
  expect(cardData[108].type).toBe("Armor Mod")
  expect(cardData[108].description).toBe("Increases your chance of finding ammo while you have a Linear Fusion Rifle equipped.")
  expect(cardData[108].icon).toBe("https://bungie.net/common/destiny2_content/icons/f48292aa6d351e3c1f8fb4a74502c239.png")
  expect(cardData[108].timesSold).toBe(1)
  expect(cardData[108].lastSold).toBe("2020-11-15")
  expect(cardData[109].name).toBe("Submachine Gun Reserves")
  expect(cardData[109].type).toBe("Armor Mod")
  expect(cardData[109].description).toBe("Increases the amount of Submachine Gun ammo you can carry.")
  expect(cardData[109].icon).toBe("https://bungie.net/common/destiny2_content/icons/3e03c74c690ad0537d5ae95ce183f383.png")
  expect(cardData[109].timesSold).toBe(3)
  expect(cardData[109].lastSold).toBe("2020-11-14")
  expect(cardData[110].name).toBe("Machine Gun Dexterity")
  expect(cardData[110].type).toBe("Armor Mod")
  expect(cardData[110].description).toBe("Faster ready and stow speed for Machine Guns.")
  expect(cardData[110].icon).toBe("https://bungie.net/common/destiny2_content/icons/11e2f4844a9cffd30dfc1b1e065a6ef0.png")
  expect(cardData[110].timesSold).toBe(4)
  expect(cardData[110].lastSold).toBe("2020-11-12")
  expect(cardData[111].name).toBe("Shotgun Ammo Finder")
  expect(cardData[111].type).toBe("Armor Mod")
  expect(cardData[111].description).toBe("Increases your chance of finding ammo while you have a Shotgun equipped.")
  expect(cardData[111].icon).toBe("https://bungie.net/common/destiny2_content/icons/5ab48ede85a6972d2c0b1f4bc5bcb640.png")
  expect(cardData[111].timesSold).toBe(5)
  expect(cardData[111].lastSold).toBe("2020-11-11")
  expect(cardData[112].name).toBe("Pulse Rifle Targeting")
  expect(cardData[112].type).toBe("Armor Mod")
  expect(cardData[112].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Pulse Rifles.")
  expect(cardData[112].icon).toBe("https://bungie.net/common/destiny2_content/icons/5c8b9e5bc6be59d0c94437f7ae03bb12.png")
  expect(cardData[112].timesSold).toBe(2)
  expect(cardData[112].lastSold).toBe("2020-11-10")
  expect(cardData[113].name).toBe("Light Conductor")
  expect(cardData[113].type).toBe("Armor Mod")
  expect(cardData[113].description).toBe("This mod has been deprecated and no longer functions. You may replace it with another mod.")
  expect(cardData[113].icon).toBe("https://bungie.net/common/destiny2_content/icons/58afd7d17e7b58883b94fd5ba2e66b76.png")
  expect(cardData[113].timesSold).toBe(4)
  expect(cardData[113].lastSold).toBe("2020-11-08")
  expect(cardData[114].name).toBe("Bleeding Edge")
  expect(cardData[114].type).toBe("Armor Mod")
  expect(cardData[114].description).toBe("This mod has been deprecated and no longer functions. You may replace it with another mod.")
  expect(cardData[114].icon).toBe("https://bungie.net/common/destiny2_content/icons/58afd7d17e7b58883b94fd5ba2e66b76.png")
  expect(cardData[114].timesSold).toBe(2)
  expect(cardData[114].lastSold).toBe("2020-11-05")
  expect(cardData[115].name).toBe("Grenade Launcher Dexterity")
  expect(cardData[115].type).toBe("Armor Mod")
  expect(cardData[115].description).toBe("Faster ready and stow speed for Grenade Launchers.")
  expect(cardData[115].icon).toBe("https://bungie.net/common/destiny2_content/icons/d20a351956b61019aa7b8950496a8ec0.png")
  expect(cardData[115].timesSold).toBe(1)
  expect(cardData[115].lastSold).toBe("2020-11-04")
  expect(cardData[116].name).toBe("Shotgun Reserves")
  expect(cardData[116].type).toBe("Armor Mod")
  expect(cardData[116].description).toBe("Increases the amount of Shotgun ammo you can carry.")
  expect(cardData[116].icon).toBe("https://bungie.net/common/destiny2_content/icons/a302feb7fbe96fce0fd9b300aa1bca3f.png")
  expect(cardData[116].timesSold).toBe(1)
  expect(cardData[116].lastSold).toBe("2020-10-30")
  expect(cardData[117].name).toBe("Rage of the Warmind")
  expect(cardData[117].type).toBe("Warmind Cell Mod")
  expect(cardData[117].description).toBe("Adds additional Solar damage to the explosions of Warmind Cells you destroy.")
  expect(cardData[117].icon).toBe("https://bungie.net/common/destiny2_content/icons/41e2c3607cef7cc665417dde5172ea32.png")
  expect(cardData[117].timesSold).toBe(1)
  expect(cardData[117].lastSold).toBe("2020-10-25")
  expect(cardData[118].name).toBe("Fusion Rifle Targeting")
  expect(cardData[118].type).toBe("Armor Mod")
  expect(cardData[118].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Fusion Rifles.")
  expect(cardData[118].icon).toBe("https://bungie.net/common/destiny2_content/icons/43d53063d48ec188c3a6c0287403608c.png")
  expect(cardData[118].timesSold).toBe(1)
  expect(cardData[118].lastSold).toBe("2020-10-24")
  expect(cardData[119].name).toBe("Fusion Rifle Ammo Finder")
  expect(cardData[119].type).toBe("Armor Mod")
  expect(cardData[119].description).toBe("Increases your chance of finding Special ammo while you have a Fusion Rifle equipped.")
  expect(cardData[119].icon).toBe("https://bungie.net/common/destiny2_content/icons/a668d5527a48876715d2b630a238fa71.png")
  expect(cardData[119].timesSold).toBe(3)
  expect(cardData[119].lastSold).toBe("2020-10-23")
  expect(cardData[120].name).toBe("Scout Rifle Loader")
  expect(cardData[120].type).toBe("Armor Mod")
  expect(cardData[120].description).toBe("Increases reload speed of Scout Rifles.")
  expect(cardData[120].icon).toBe("https://bungie.net/common/destiny2_content/icons/5a5e2adbbde813d46ac459960cbe8435.png")
  expect(cardData[120].timesSold).toBe(4)
  expect(cardData[120].lastSold).toBe("2020-10-17")
  expect(cardData[121].name).toBe("Remote Connection")
  expect(cardData[121].type).toBe("Armor Mod")
  expect(cardData[121].description).toBe("This mod has been deprecated and no longer functions. You may replace it with another mod.")
  expect(cardData[121].icon).toBe("https://bungie.net/common/destiny2_content/icons/58afd7d17e7b58883b94fd5ba2e66b76.png")
  expect(cardData[121].timesSold).toBe(3)
  expect(cardData[121].lastSold).toBe("2020-10-10")
  expect(cardData[122].name).toBe("Linear Fusion Rifle Scavenger")
  expect(cardData[122].type).toBe("Armor Mod")
  expect(cardData[122].description).toBe("Linear Fusion Rifles get bonus reserves when you pick up ammo.")
  expect(cardData[122].icon).toBe("https://bungie.net/common/destiny2_content/icons/81220058001d0ab32c6833624dabae3f.png")
  expect(cardData[122].timesSold).toBe(4)
  expect(cardData[122].lastSold).toBe("2020-10-09")
  expect(cardData[123].name).toBe("Unflinching Sidearm Aim")
  expect(cardData[123].type).toBe("Armor Mod")
  expect(cardData[123].description).toBe("Reduces flinching from incoming fire while aiming Sidearms.")
  expect(cardData[123].icon).toBe("https://bungie.net/common/destiny2_content/icons/128abd9ae18efbb7683826413117cd57.png")
  expect(cardData[123].timesSold).toBe(4)
  expect(cardData[123].lastSold).toBe("2020-10-05")
  expect(cardData[124].name).toBe("Light of the Fire")
  expect(cardData[124].type).toBe("Warmind Cell Mod")
  expect(cardData[124].description).toBe("Rapidly defeating targets with the detonation of a Warmind Cell generates an Orb of Power.")
  expect(cardData[124].icon).toBe("https://bungie.net/common/destiny2_content/icons/bd59d9404b500d7dafb9038a149d8d1d.png")
  expect(cardData[124].timesSold).toBe(1)
  expect(cardData[124].lastSold).toBe("2020-10-04")
  expect(cardData[125].name).toBe("Fireteam Medic")
  expect(cardData[125].type).toBe("Warmind Cell Mod")
  expect(cardData[125].description).toBe("Destroying a Warmind Cell creates a burst of healing for you and allies near you.")
  expect(cardData[125].icon).toBe("https://bungie.net/common/destiny2_content/icons/1b0357512d53319f63e5d2bf3c0a17b7.png")
  expect(cardData[125].timesSold).toBe(1)
  expect(cardData[125].lastSold).toBe("2020-09-24")
  expect(cardData[126].name).toBe("Powerful Friends")
  expect(cardData[126].type).toBe("Charged with Light Mod")
  expect(cardData[126].description).toBe("When you become Charged with Light, nearby allies also become Charged with Light, if they are not already.")
  expect(cardData[126].icon).toBe("https://bungie.net/common/destiny2_content/icons/006460670f0ca57fbe5ee1af83dcfd4d.png")
  expect(cardData[126].timesSold).toBe(2)
  expect(cardData[126].lastSold).toBe("2020-09-22")
  expect(cardData[127].name).toBe("Linear Fusion Rifle Reserves")
  expect(cardData[127].type).toBe("Armor Mod")
  expect(cardData[127].description).toBe("Increases the amount of Linear Fusion Rifle ammo you can carry.")
  expect(cardData[127].icon).toBe("https://bungie.net/common/destiny2_content/icons/56d897309f2d48bad31228a28e0c556a.png")
  expect(cardData[127].timesSold).toBe(2)
  expect(cardData[127].lastSold).toBe("2020-09-21")
  expect(cardData[128].name).toBe("Rocket Launcher Loader")
  expect(cardData[128].type).toBe("Armor Mod")
  expect(cardData[128].description).toBe("Increases reload speed of Rocket Launchers.")
  expect(cardData[128].icon).toBe("https://bungie.net/common/destiny2_content/icons/776cbdeb79b0e5b002daa1eed3330fe2.png")
  expect(cardData[128].timesSold).toBe(7)
  expect(cardData[128].lastSold).toBe("2020-09-18")
  expect(cardData[129].name).toBe("Sniper Rifle Ammo Finder")
  expect(cardData[129].type).toBe("Armor Mod")
  expect(cardData[129].description).toBe("Increases your chance of finding ammo while you have a Sniper Rifle equipped.")
  expect(cardData[129].icon).toBe("https://bungie.net/common/destiny2_content/icons/32501a5e9478cc1cf294aaf14de7924d.png")
  expect(cardData[129].timesSold).toBe(4)
  expect(cardData[129].lastSold).toBe("2020-09-16")
  expect(cardData[130].name).toBe("Sword Scavenger")
  expect(cardData[130].type).toBe("Armor Mod")
  expect(cardData[130].description).toBe("Swords get bonus reserves when you pick up ammo.")
  expect(cardData[130].icon).toBe("https://bungie.net/common/destiny2_content/icons/1d408256bf3d9a8aebfd9249190998cc.png")
  expect(cardData[130].timesSold).toBe(1)
  expect(cardData[130].lastSold).toBe("2020-09-14")
  expect(cardData[131].name).toBe("Scout Rifle Reserves")
  expect(cardData[131].type).toBe("Armor Mod")
  expect(cardData[131].description).toBe("Increases the amount of Scout Rifle ammo you can carry.")
  expect(cardData[131].icon).toBe("https://bungie.net/common/destiny2_content/icons/8e291ed73aab71c45bc74826a9941847.png")
  expect(cardData[131].timesSold).toBe(1)
  expect(cardData[131].lastSold).toBe("2020-08-26")
  expect(cardData[132].name).toBe("Bow Targeting")
  expect(cardData[132].type).toBe("Armor Mod")
  expect(cardData[132].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Bows.")
  expect(cardData[132].icon).toBe("https://bungie.net/common/destiny2_content/icons/a5121e051f0aeaa9eb39c90652ae68c6.png")
  expect(cardData[132].timesSold).toBe(2)
  expect(cardData[132].lastSold).toBe("2020-08-17")
  expect(cardData[133].name).toBe("Scout Rifle Targeting")
  expect(cardData[133].type).toBe("Armor Mod")
  expect(cardData[133].description).toBe("Improved target acquisition, accuracy, and aim-down-sights speed for Scout Rifles.")
  expect(cardData[133].icon).toBe("https://bungie.net/common/destiny2_content/icons/812fae884f6deb3850d7e14104ecf9d5.png")
  expect(cardData[133].timesSold).toBe(5)
  expect(cardData[133].lastSold).toBe("2020-08-16")
  expect(cardData[134].name).toBe("Hand Cannon Scavenger")
  expect(cardData[134].type).toBe("Armor Mod")
  expect(cardData[134].description).toBe("Hand Cannons get bonus reserves when you pick up ammo.")
  expect(cardData[134].icon).toBe("https://bungie.net/common/destiny2_content/icons/deb9ea8b84e7b15620d8a31d1755c76f.png")
  expect(cardData[134].timesSold).toBe(2)
  expect(cardData[134].lastSold).toBe("2020-08-13")
  expect(cardData[135].name).toBe("Storm of Lead")
  expect(cardData[135].type).toBe("Armor Mod")
  expect(cardData[135].description).toBe("This mod has been deprecated and no longer functions. You may replace it with another mod.")
  expect(cardData[135].icon).toBe("https://bungie.net/common/destiny2_content/icons/58afd7d17e7b58883b94fd5ba2e66b76.png")
  expect(cardData[135].timesSold).toBe(4)
  expect(cardData[135].lastSold).toBe("2020-08-04")
  expect(cardData[136].name).toBe("Grenade Launcher Ammo Finder")
  expect(cardData[136].type).toBe("Armor Mod")
  expect(cardData[136].description).toBe("Increases your chance of finding ammo while you have a Grenade Launcher equipped.")
  expect(cardData[136].icon).toBe("https://bungie.net/common/destiny2_content/icons/292a3b4ede46b4de5a392232cf9fd80c.png")
  expect(cardData[136].timesSold).toBe(4)
  expect(cardData[136].lastSold).toBe("2020-07-29")
  expect(cardData[137].name).toBe("Bow Dexterity")
  expect(cardData[137].type).toBe("Armor Mod")
  expect(cardData[137].description).toBe("Faster ready and stow speed for Bows.")
  expect(cardData[137].icon).toBe("https://bungie.net/common/destiny2_content/icons/bcdc82bb7b3d32d11cce08ac4db1f745.png")
  expect(cardData[137].timesSold).toBe(4)
  expect(cardData[137].lastSold).toBe("2020-07-18")
  expect(cardData[138].name).toBe("Shotgun Loader")
  expect(cardData[138].type).toBe("Armor Mod")
  expect(cardData[138].description).toBe("Increases reload speed of Shotguns.")
  expect(cardData[138].icon).toBe("https://bungie.net/common/destiny2_content/icons/12d6b0e57bc1ceff6cfa637e09674b4b.png")
  expect(cardData[138].timesSold).toBe(1)
  expect(cardData[138].lastSold).toBe("2020-07-17")
  expect(cardData[139].name).toBe("Dire Artillery")
  expect(cardData[139].type).toBe("Armor Mod")
  expect(cardData[139].description).toBe("This mod has been deprecated and no longer functions. You may replace it with another mod.")
  expect(cardData[139].icon).toBe("https://bungie.net/common/destiny2_content/icons/58afd7d17e7b58883b94fd5ba2e66b76.png")
  expect(cardData[139].timesSold).toBe(1)
  expect(cardData[139].lastSold).toBe("2020-07-11")
  expect(cardData[140].name).toBe("Cellular Suppression")
  expect(cardData[140].type).toBe("Warmind Cell Mod")
  expect(cardData[140].description).toBe("Damaging a Warmind Cell creates a burst of suppressing Void energy. Additionally, you deal less damage to Warmind Cells.")
  expect(cardData[140].icon).toBe("https://bungie.net/common/destiny2_content/icons/ba4111a459ca971860571ef9ce5ca4ed.png")
  expect(cardData[140].timesSold).toBe(2)
  expect(cardData[140].lastSold).toBe("2020-07-08")
  expect(cardData[141].name).toBe("Unflinching Shotgun Aim")
  expect(cardData[141].type).toBe("Armor Mod")
  expect(cardData[141].description).toBe("Reduces flinching from incoming fire while aiming Shotguns.")
  expect(cardData[141].icon).toBe("https://bungie.net/common/destiny2_content/icons/ba6b4de9111248e5d772ccd97f4b36ff.png")
  expect(cardData[141].timesSold).toBe(3)
  expect(cardData[141].lastSold).toBe("2020-07-06")
  expect(cardData[142].name).toBe("Auto Rifle Dexterity")
  expect(cardData[142].type).toBe("Armor Mod")
  expect(cardData[142].description).toBe("Faster ready and stow speed for Auto Rifles and Trace Rifles.")
  expect(cardData[142].icon).toBe("https://bungie.net/common/destiny2_content/icons/34da39d9d7a4511d16d79a329da0874c.png")
  expect(cardData[142].timesSold).toBe(2)
  expect(cardData[142].lastSold).toBe("2020-07-02")
  expect(cardData[143].name).toBe("Unflinching Bow Aim")
  expect(cardData[143].type).toBe("Armor Mod")
  expect(cardData[143].description).toBe("Reduces flinching from incoming fire while aiming Bows.")
  expect(cardData[143].icon).toBe("https://bungie.net/common/destiny2_content/icons/751903f60aac49ccaa94c243e7780321.png")
  expect(cardData[143].timesSold).toBe(1)
  expect(cardData[143].lastSold).toBe("2020-07-01")
  expect(cardData[144].name).toBe("Light Reactor")
  expect(cardData[144].type).toBe("Armor Mod")
  expect(cardData[144].description).toBe("This mod has been deprecated and no longer functions. You may replace it with another mod.")
  expect(cardData[144].icon).toBe("https://bungie.net/common/destiny2_content/icons/58afd7d17e7b58883b94fd5ba2e66b76.png")
  expect(cardData[144].timesSold).toBe(1)
  expect(cardData[144].lastSold).toBe("2020-06-23")
  expect(cardData[145].name).toBe("Machine Gun Scavenger")
  expect(cardData[145].type).toBe("Armor Mod")
  expect(cardData[145].description).toBe("Machine Guns get bonus reserves when you pick up ammo.")
  expect(cardData[145].icon).toBe("https://bungie.net/common/destiny2_content/icons/31caef1935f19a168b3a44c4d0a19409.png")
  expect(cardData[145].timesSold).toBe(2)
  expect(cardData[145].lastSold).toBe("2020-06-16")
  expect(cardData[146].name).toBe("Firepower")
  expect(cardData[146].type).toBe("Charged with Light Mod")
  expect(cardData[146].description).toBe("While Charged with Light, regain a portion of your grenade energy when you use your grenade, consuming one stack of Charged with Light.")
  expect(cardData[146].icon).toBe("https://bungie.net/common/destiny2_content/icons/070b7b77cd6fb8462dc6013764cb3709.png")
  expect(cardData[146].timesSold).toBe(2)
  expect(cardData[146].lastSold).toBe("2020-05-10")
  expect(cardData[147].name).toBe("Sniper Rifle Loader")
  expect(cardData[147].type).toBe("Armor Mod")
  expect(cardData[147].description).toBe("Increases reload speed of Sniper Rifles.")
  expect(cardData[147].icon).toBe("https://bungie.net/common/destiny2_content/icons/87e6d89dda2ea208b49d90e47af8fb9e.png")
  expect(cardData[147].timesSold).toBe(1)
  expect(cardData[147].lastSold).toBe("2020-05-01")
  /* eslint-disable max-len */
})
